apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: "exercise-03"
  labels:
    app: wordpress
spec:
  sessionAffinity: ClientIP
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
    nodePort: 30000
  - name: https
    protocol: TCP
    port: 443
    targetPort: https
    nodePort: 30001
  selector:
    app: wordpress