apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mariadb-master
  namespace: exercise-02
  labels:
    app: mariadb
    role: master
# From here it's a RS
spec:
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
      role: master
  template:
    metadata:
      labels:
        app: mariadb
        role: master
        app-served: wordpress
# From here, it's a POD
    spec:
      containers:
      - name: master
        image: bitnami/mariadb:latest
        ports:
        - name: mysql
          containerPort: 3306
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: rootpass
        - name: MARIADB_USER
          valueFrom:
            configMapKeyRef:
              name: mariadb
              key: maria-user
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: userpass
        - name: MARIADB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mariadb
              key: database-name
        - name: MARIADB_REPLICATION_MODE
          value: master
        - name: MARIADB_REPLICATION_USER
          valueFrom:
            configMapKeyRef:
              name: mariadb
              key: replic-user
        - name: MARIADB_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: replic-pass
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "mysqladmin ping -u${MARIADB_USER} -p${MARIADB_PASSWORD}"
          initialDelaySeconds: 10
          failureThreshold: 5
          timeoutSeconds: 1
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "mysqladmin ping -u${MARIADB_USER} -p${MARIADB_PASSWORD}"
          initialDelaySeconds: 15
          periodSeconds: 30
