apiVersion: "v1"
kind: "Service"
metadata:
  name: mariadb-slave
  namespace: exercise-02
  labels:
    app: mariadb
    role: slave
spec:
  type: ClusterIP
  selector:
    app: mariadb
    role: slave
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql