apiVersion: "v1"
kind: "Service"
metadata:
  name: wordpress
  namespace: exercise-02
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
