apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
    tier: frontend
  name: wordpress-external
  namespace: exercise-01
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
  selector:
    app: wordpress
    tier: frontend
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
    tier: frontend
  name: wordpress-internal
  namespace: exercise-01
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
  selector:
    app: wordpress
    tier: frontend