apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mariadb
  namespace: exercise01
  labels: 
    app: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata: 
      labels:
        app: mariadb   
    spec:
      containers:
      - image: bitnami/mariadb:latest
        name: mariadb
        livenessProbe:
          exec:
            command: ["sh", "-c", "exec mysqladmin status -uroot -p$MARIADB_ROOT_PASSWORD"]
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          exec:
            command: ["sh", "-c", "exec mysqladmin status -uroot -p$MARIADB_ROOT_PASSWORD"]
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 5
        env:
          - name: ALLOW_EMPTY_PASSWORD 
            value: "yes"
          - name: MARIADB_USER
            valueFrom:
              configMapKeyRef:
                name: ex01configmap
                key: MARIADB_USER
          - name: MARIADB_DATABASE 
            valueFrom:
              configMapKeyRef:
                name: ex01configmap
                key: MARIADB_DATABASE  
        ports: 
          - name: mariadbport
            containerPort: 3306

      # MARIADB_DATABASE=my_database