apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress-canary
  namespace: exercise01
  labels:
    app: wordpress
spec:
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      version: canary
  template:
    metadata: 
      labels:
        app: wordpress
        version: canary
    spec:
      containers:
      - image: bitnami/wordpress:4.9.8
        name: wordpress
        livenessProbe:
          httpGet:
            path: /wp-login.php
            port: http
          initialDelaySeconds: 20
        readinessProbe:
          httpGet:
            path: /wp-login.php
            port: http
          initialDelaySeconds: 15
        env: 
          - name: ALLOW_EMPTY_PASSWORD
            value: "yes"
          - name: MARIADB_HOST
            valueFrom:
              configMapKeyRef:
                name: ex01configmap
                key: MARIADB_HOST
          - name: MARIADB_PORT_NUMBER
            valueFrom:
              configMapKeyRef:
                name: ex01configmap
                key: MARIADB_PORT_NUMBER
          - name: WORDPRESS_DATABASE_USER
            valueFrom:
              configMapKeyRef:
                name: ex01configmap
                key: MARIADB_USER
          - name: WORDPRESS_DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: ex01configmap
                key: MARIADB_DATABASE  
        ports:
          - name: http
            containerPort: 80
          - name: https
            containerPort: 443
