apiVersion: "v1"
kind: "Service"
metadata:
  name: myblog-mariadb
  namespace: exercise-01
  labels:
    app: myblog
    tier: backend
spec:
  ports:
  - port: 3306
    targetPort: mariadb
  selector:
    app: myblog
    tier: backend
  type: ClusterIP
