apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myblog-wordpress
  namespace: exercise-01
  labels:
    app: myblog
    tier: frontend
    track: stable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myblog
      tier: frontend
      track: stable
  template:
    metadata:
      labels:
        app: myblog
        tier: frontend
        track: stable
    spec:
      containers:
      - image: bitnami/wordpress:4.9.8
        name: wordpress
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
        - name: WORDPRESS_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: myblog
              key: WORDPRESS_DATABASE_NAME
        - name: WORDPRESS_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: myblog
              key: WORDPRESS_DATABASE_USER
        - name: WORDPRESS_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: myblog
              key: WORDPRESS_DATABASE_PASSWORD
        - name: WORDPRESS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: myblog
              key: WORDPRESS_PASSWORD
        envFrom:
          - configMapRef:
              name: myblog
        ports: 
          - name: http
            containerPort: 80
          - name: https
            containerPort: 443
            
