---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-master
  namespace: exercise-02
  labels:
    app: mariadb-master
data:
  MARIADB_DATABASE: bitnami_wordpress
  MARIADB_USER: bn_wordpress
  MARIADB_REPLICATION_MODE: master
  MARIADB_REPLICATION_USER: replicator

