############################ # ############################
## Bitnami K8S training
## session02/exercise01
#
## Author: Antonio Gamez-Diaz
## Contact: antoniogamez@us.es
#
# File: mariadb configmap creation
# Purpose: creates key/value pairs to be used in mariadb
############################ # ############################
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-slave-env-cm
  namespace: s02-exercise-01
  labels:
    app: mariadb
    tier: database
    role: slave
data:
  MARIADB_USER: dbuser
  MARIADB_DATABASE: database
  MARIADB_REPLICATION_MODE: slave
  MARIADB_REPLICATION_USER: replication-user
  MARIADB_MASTER_HOST: mariadb
  MARIADB_MASTER_ROOT_PORT: "3306"