apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress
  namespace: exercise-01
  labels:
    app: wordpress
    tier: frontend
    release: production
spec:
  revisionHistoryLimit: 3
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
      release: production
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
        release: production
    spec:
      containers:
      - name: wordpress
        image: bitnami/wordpress:4.9.7
        ports:
        - name: http-server
          containerPort: 80
        env:
          - name: MARIADB_HOST
            valueFrom:
              configMapKeyRef:
                name: wordpress-config
                key: mariadb-host
          - name: WORDPRESS_DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: wp-dbname
          - name: WORDPRESS_DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: wp-user
          - name: WORDPRESS_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: wp-password
          - name: WORDPRESS_USERNAME
            valueFrom:
              secretKeyRef:
                name: wp-credentials
                key: user
          - name: WORDPRESS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wp-credentials
                key: password
          - name: WORDPRESS_BLOG_NAME
            valueFrom:
              configMapKeyRef:
                name: wordpress-config
                key: blog-name
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /wp-login.php
            port: 80
          initialDelaySeconds: 300
          periodSeconds: 30
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /wp-login.php
            port: 80
          initialDelaySeconds: 180
          periodSeconds: 15
