apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drupal
  namespace: exercise-01
  labels:
    app: drupal
    tier: frontend
    release: production
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app: drupal
      tier: frontend
      release: production
  template:
    metadata:
      labels:
        app: drupal
        tier: frontend
        release: production
    spec:
      containers:
      - name: drupal
        image: bitnami/drupal:8.6.1
        volumeMounts:
        - mountPath: /bitnami
          name: drupal-data
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        resources:
          requests:
            cpu: "40m"
            memory: "250Mi"
          limits:
            cpu: "80m"
            memory: "500Mi"
        env:
        - name: NAMI_DEBUG
          value: "1"
        - name: MARIADB_HOST
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: mariadb-host
        - name: DRUPAL_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: dr-dbname
        - name: DRUPAL_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: dr-user
        - name: DRUPAL_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: dr-password
        - name: WORDPRESS_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: dr-password
        - name: DRUPAL_USERNAME
          valueFrom:
            secretKeyRef:
              name: dr-credentials
              key: user
        - name: DRUPAL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dr-credentials
              key: password
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: root-password
        - name: MYSQL_CLIENT_CREATE_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: dr-dbname
        - name: MYSQL_CLIENT_CREATE_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: dr-user
        - name: MYSQL_CLIENT_CREATE_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: dr-password
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /user/login
            port: http
          initialDelaySeconds: 540
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /user/login
            port: http
          initialDelaySeconds: 480
      volumes:
      - name: drupal-data
        persistentVolumeClaim:
          claimName: drupal-pvc
