apiVersion: v1
kind: Service
metadata:
  name: mariadbslave
  namespace: exercise02
  labels:
    app: mariadb
    component: slave
spec:
  type: ClusterIP
  ports: 
    - port: 3306
      targetPort: mariadbport
  selector: 
    app: mariadb
    component: slave



  