apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: exercise02
  labels:
    app: mariadb
    component: master
spec:
  type: ClusterIP
  ports: 
    - port: 3306
      targetPort: mariadbport
  selector: 
    app: mariadb
    component: master



  