apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  namespace: exercise02
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
    - port: 80 
      targetPort: http
  selector: 
    app: wordpress
  