apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mariadb
  namespace: "exercise-01"
# From here it's a RS
spec:
  # replicas: 2
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
        app-served: wordpress
# From here, it's a POD
    spec:
      containers:
      - name: mariadb
        image: bitnami/mariadb:latest
        ports:
        - name: mysql
          containerPort: 3306
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: rootpass
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: maria-user
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: userpass
        - name: MARIADB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mariadb
              key: database-name
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "mysqladmin ping -u${MARIADB_USER} -p${MARIADB_PASSWORD}"
          initialDelaySeconds: 10
          failureThreshold: 5
          timeoutSeconds: 1
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "mysqladmin ping -u${MARIADB_USER} -p${MARIADB_PASSWORD}"
          initialDelaySeconds: 15
          periodSeconds: 10