apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress
  namespace: "exercise-01"
  labels:
    app: wordpress
# From here it's a RS
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      track: stable
  template:
    metadata:
      labels:
        app: wordpress
        track: stable
        app-served: none
# From here, it's a POD
    spec:
      containers:
      - image: bitnami/wordpress:4.9.7
        name: wordpress
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: https
          containerPort: 443
          protocol: TCP
        env:
        - name: WORDPRESS_BLOG_NAME
          valueFrom:
            configMapKeyRef:
              name: wordpress
              key: wp-blogname
        - name: WORDPRESS_USERNAME
          valueFrom:
            secretKeyRef:
              name: wordpress
              key: wp-username
        - name: WORDPRESS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress
              key: wp-password
        - name: WORDPRESS_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress
              key: dbpass
        - name: WORDPRESS_DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: wordpress
              key: database
        - name: WORDPRESS_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: wordpress
              key: db-user
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          failureThreshold: 5
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 30