apiVersion: "v1"
kind: "Service"
metadata:
  name: wordpress
  namespace: "exercise-01"
spec:
  type: NodePort
  ports:
  - nodePort: 80
    protocol: TCP
    port: 80
    targetPort: http
  - nodePort: 443
    protocol: TCP
    port: 443
    targetPort: https
  selector:
    app: wordpress
  sessionAffinity: ClientIP
