apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
    tier: mariadb
  name: mariadb-slave
  namespace: exercise-02
spec:
  type: ClusterIP
  ports:
  - name: mariadb
    port: 3306
  selector:
    app: wordpress
    tier: mariadb
    mode: slave