############################ # ############################
## Bitnami K8S training
## session02/exercise02
#
## Author: Antonio Gamez-Diaz
## Contact: antoniogamez@us.es
#
# File: mariadb-master secret creation
# Purpose: creates b64-encoded secrets for mariadb-master
############################ # ############################
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadbdump-secret
  namespace: s02-exercise-02
  labels:
    app: mariadb
    tier: database
type: Opaque
data:
  dbuser: dG9vcg== # toor
  dbpass: cm9vdF9wYXNzd29yZA== # root_password