apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mariadb-master
  namespace: exercise-02
  labels:
    app: mariadb
    role: master
spec:
  revisionHistoryLimit: 2
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: mariadb
      role: master
  template:
    metadata:
      labels:
        app: mariadb
        role: master
    spec:
      containers:
      - image: bitnami/mariadb:latest
        name: mariadb
        ports:
        - name: tcp
          containerPort: 3306
        env:
          - name: MARIADB_REPLICATION_MODE
            value: master
          - name: MARIADB_REPLICATION_USER
            value: repl_user
          - name: MARIADB_REPLICATION_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-secrets
                key: repl-password
          - name: MARIADB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: database-config
                key: database-name
          - name: MARIADB_ROOT_USER
            valueFrom:
              configMapKeyRef:
                name: database-config
                key: database-user
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-secrets
                key: root-password
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
