apiVersion: v1
kind: Service
metadata:
  name: mariadb-slave
  namespace: exercise-02
spec:
  type: ClusterIP
  ports:
  - name: database-connection
    port: 3306
  selector:
    app: mariadb
    role: slave
