apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress-stable
  namespace: exercise-01
spec:
  revisionHistoryLimit: 2
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: wordpress
      environment: stable
  template:
    metadata:
      labels:
        app: wordpress
        environment: stable
    spec:
      containers:
      - image: bitnami/wordpress:4.9.7
        name: wordpress-stable
        ports:
        - name: http
          containerPort: 80
        env:
          - name: WORDPRESS_DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: database-config
                key: database-name
          - name: WORDPRESS_DATABASE_USER
            valueFrom:
              configMapKeyRef:
                name: database-config
                key: database-user
          - name: WORDPRESS_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-secrets
                key: root-password
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
