apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: exercise-01
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
  - name: http-server
    port: 80
    targetPort: 80
  selector:
    app: wordpress
