# ############################ # ############################
# ## Bitnami K8S training
# ## session01/exercise02
# #
# ## Author: Antonio Gamez-Diaz
# ## Contact: antoniogamez@us.es
# #
# # File: production Let's Encrypt cert issuer
# # Purpose: connects to ACMEv2 production endpoint to request a new cert
# ############################ # ############################
# ---
# apiVersion: certmanager.k8s.io/v1alpha1
# kind: Issuer
# metadata:
#   name: letsencrypt-production
#   namespace: s02-exercise-01
# spec:
#   acme:
#     server: https://acme-v02.api.letsencrypt.org/directory
#     email: antgamdia@gmail.com
#     privateKeySecretRef:
#       name: letsencrypt-production
#     http01: {}