apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: exercise-02
  labels:
    app: exercise-02
spec:
  type: ClusterIP
  ports:
    - name: tcp
      port: 3306
      targetPort: tcp
  selector:
    name: mariadb

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: exercise-02
  labels:
    app: exercise-02
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    name: wordpress