apiVersion: v1
kind: Service
metadata:
  name: mariadb-slave
  namespace: exercise-02
  labels:
    app: mariadb
    tier: backend
    role: slave
spec:
  type: ClusterIP
  ports:
    - name: data
      port: 3306
      targetPort: mariadb-server
  selector:
    app: mariadb
    tier: backend
    role: slave
