apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: exercise-02
  labels:
    app: wordpress
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - name: frontend
      port: 80
      targetPort: http-server
  selector:
    app: wordpress
    tier: frontend
