apiVersion: v1
kind: Service
metadata:
  name: mariadb-master
  namespace: exercise-02
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: mariadb
    tier: database
    component: master
