apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress
  namespace: exercise-02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      initContainers:
      - name: download-hyperdb
        image: bitnami/minideb
        command:
          - bash
          - -ec
          - |
             # Install required system packages
             install_packages unzip ca-certificates curl
             # Download HyperDB Plugin             
             cd /tmp/
             curl -Lo hyperdb.zip https://downloads.wordpress.org/plugin/hyperdb.zip
             unzip hyperdb.zip             
        volumeMounts:
        - mountPath: /tmp/hyperdb
          name: hyperdb-files          
      containers:
      - name: wordpress
        image: bitnami/wordpress:latest
        env:
        - name: MARIADB_HOST
          value: "mariadb-master"
        - name: MARIADB_PORT_NUMBER
          value: "3306"
        - name: WORDPRESS_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: database-name
        - name: WORDPRESS_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: database-user
        - name: WORDPRESS_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: database-password
        - name: WORDPRESS_USERNAME
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: user
        - name: WORDPRESS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: password
        - name: WORDPRESS_BLOG_NAME
          valueFrom:
            configMapKeyRef:
              name: wordpress-configmap
              key: blog-name
        - name: WORDPRESS_FIRST_NAME
          valueFrom:
            configMapKeyRef:
              name: wordpress-configmap
              key: admin-first-name
        - name: WORDPRESS_LAST_NAME
          valueFrom:
            configMapKeyRef:
              name: wordpress-configmap
              key: admin-last-name
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        # resources:
        #   requests:
        #     memory: 512Mi
        #     cpu: 200m
        #   limits:
        #     memory: 768Mi
        #     cpu: 400m
        livenessProbe:
          initialDelaySeconds: 120
          httpGet:
            path: /wp-login.php
            port: http
        readinessProbe:
          initialDelaySeconds: 30
          httpGet:
            path: /wp-login.php
            port: http
        volumeMounts:
        - mountPath: /tmp/hyperdb
          name: hyperdb-files
        - mountPath: /tmp/hyperdb-script
          name: hyperdb-script
        - mountPath: /bitnami/apache
          name: wordpress-data
          subPath: apache
        - mountPath: /bitnami/wordpress
          name: wordpress-data
          subPath: wordpress
        - mountPath: /bitnami/php
          name: wordpress-data
          subPath: php
      volumes:
      - name: wordpress-data
        emptyDir: {}
      - name: hyperdb-files
        emptyDir: {}
      - name: hyperdb-script
        configMap:
          name: hyperdb-script
          defaultMode: 0744        
