apiVersion: v1
kind: Service
metadata:
  name: mariadb-slave
  namespace: exercise-02
  labels:
    app: wordpress
    role: slave
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: mariadb-server
  selector:
    app: wordpress
    role: slave
    tier: backend
