apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  namespace: exercise-02
  labels:
    app: wordpress
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http-port
      nodePort: 32520
  selector:
    app: wordpress
    tier: frontend
