apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-mariadb
  namespace: exercise-01
data:
  mariadb_database: "wordpress"
  mariadb_port: "3306"
  mariadb_master_host: "mariadb-master"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-wordpress
  namespace: exercise-01
data:
  wordpress_blog_name: "Kubernetes"