############################ # ############################
## Bitnami K8S training
## session01/exercise02
#
## Author: Antonio Gamez-Diaz
## Contact: antoniogamez@us.es
#
# File: wordpress secret creation
# Purpose: creates b64-encoded secrets for Wordpress
############################ # ############################
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: s02-exercise-01
  labels:
    app: wordpress
    tier: frontend
type: Opaque
data:
  WORDPRESS_DATABASE_NAME: ZGF0YWJhc2U= # database
  WORDPRESS_DATABASE_USER: ZGJ1c2Vy # dbuser 
  WORDPRESS_DATABASE_PASSWORD: ZGJ1c2VyX3Bhc3N3b3Jk # dbuser_password
  
  WORDPRESS_PASSWORD: YW50b25pb193cA== # antonio_wp
  WORDPRESS_USERNAME: YW50b25pbw== # antonio