# ############################ # ############################
# ## Bitnami K8S training
# ## session01/exercise03-p01
# #
# ## Author: Antonio Gamez-Diaz
# ## Contact: antoniogamez@us.es
# #
# # File: wordpress-backupper pv claim creation
# # Purpose: allocates some persistence
# ############################ # ############################
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-backupper-pvc
  namespace: s02-exercise-03-p01
  labels:
    app: wordpress
    tier: frontend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
