apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mariadb-deployment
  namespace: exercise-01
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
        tier: backend
    spec:
      containers:
      - image: bitnami/mariadb:latest
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "mysqladmin ping -u root -p${MARIADB_ROOT_PASSWORD}"
          initialDelaySeconds: 90
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "mysqladmin ping -u root -p${MARIADB_ROOT_PASSWORD}"
          initialDelaySeconds: 35
          periodSeconds: 10
        name: mariadb
        ports:
        - name: mysql-port
          containerPort: 3306
        env:
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb-secret
                key: mariadb-root-password
          - name: MARIADB_DATABASE
            valueFrom:
              secretKeyRef:
                name: mariadb-secret
                key: mariadb-database-name
          - name: MARIADB_USER
            valueFrom:
              secretKeyRef:
                name: mariadb-secret
                key: mariadb-database-user
          - name: MARIADB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb-secret
                key: mariadb-database-password
