############################ # ############################
## Bitnami K8S training
## session02/exercise03
#
## Author: Antonio Gamez-Diaz
## Contact: antoniogamez@us.es
#
# File: mariadb-master secret creation
# Purpose: creates b64-encoded secrets for mariadb-master
############################ # ############################
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-master-secret
  namespace: s02-exercise-03
  labels:
    app: mariadb
    tier: database
    role: master
type: Opaque
data:
  MARIADB_ROOT_USER: dG9vcg== # toor
  MARIADB_ROOT_PASSWORD: cm9vdF9wYXNzd29yZA== # root_password
  MARIADB_PASSWORD: ZGJ1c2VyX3Bhc3N3b3Jk # dbuser_password
  MARIADB_REPLICATION_PASSWORD: cmVwbGljYXRpb25fcGFzc3dvcmQ= # replication_password