############################ # ############################
## Bitnami K8S training
## session02/exercise03
#
## Author: Antonio Gamez-Diaz
## Contact: antoniogamez@us.es
#
# File: mariadb-master headless service
# Purpose: exposes a "mariadb" service
############################ # ############################
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: s02-exercise-03
  labels:
    app: mariadb
    tier: database
    role: master
spec:
  ports:
  - name: mariadb
    port: 3306
    targetPort: mariadb
  selector:
    app: mariadb
    tier: database
    role: master