apiVersion: v1
kind: Service
metadata:
  name: mariadb-master
  namespace: exercise-02
  labels:
    app: mariadb
    role: master
spec:
  type: ClusterIP
  ports:
    - name: mariadb-tcp
      port: 3306
      targetPort: db-master-port
  selector:
    app: mariadb
    role: master