apiVersion: v1
kind: Service
metadata:
  name: mariadb-slave
  namespace: exercise-02
  labels:
    app: mariadb
    role: slave
spec:
  type: ClusterIP
  ports:
    - name: mariadb-tcp
      port: 3306
      targetPort: db-slave-port
  selector:
    app: mariadb
    role: slave