############################ # ############################
## Bitnami K8S training
## session01/exercise02
#
## Author: Antonio Gamez-Diaz
## Contact: antoniogamez@us.es
#
# File: drupal secret creation
# Purpose: creates b64-encoded secrets for drupal
############################ # ############################
---
apiVersion: v1
kind: Secret
metadata:
  name: drupal-secret
  namespace: s02-exercise-01
  labels:
    app: drupal
type: Opaque
data:
  DRUPAL_DATABASE_NAME: ZGF0YWJhc2U= # database
  DRUPAL_DATABASE_USER: ZGJ1c2Vy # dbuser 
  DRUPAL_DATABASE_PASSWORD: ZGJ1c2VyX3Bhc3N3b3Jk # dbuser_password
  DRUPAL_PASSWORD: YW50b25pb193cA== # antonio_wp