############################ # ############################
## Bitnami K8S training
## session01/exercise02
#
## Author: Antonio Gamez-Diaz
## Contact: antoniogamez@us.es
#
# File: drupal service
# Purpose: exposes a "drupal" NodePort service through the kubedns
############################ # ############################
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: drupal
  namespace: s02-exercise-01
  labels:
    app: drupal
    tier: frontend
spec:
  selector:
    app: drupal
    tier: frontend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
    nodePort: 31081
  - name: https
    protocol: TCP
    port: 443
    targetPort: https
    nodePort: 31444
  type: NodePort