############################ # ############################
## Bitnami K8S training
## session01/exercise02
#
## Author: Antonio Gamez-Diaz
## Contact: antoniogamez@us.es
#
# File: drupal deployment creation
# Purpose: defines the pods, replicas, liveness and readiness probes for drupal
############################ # ############################
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drupal-deploy
  namespace: s02-exercise-01
  labels:
    app: drupal
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
      tier: frontend
  template:
    metadata:
      labels:
        app: drupal
        tier: frontend
    spec:
      containers:
      - name: drupal
        image: bitnami/drupal:8
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: https
          containerPort: 443
          protocol: TCP
        resources: {}
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
          # valueFrom:
          #   configMapKeyRef:
          #     name: drupal-cm
          #     key: ALLOW_EMPTY_PASSWORD
        - name: WORDPRESS_DATABASE_PASSWORD
          value: dbuser_password
          # valueFrom:
          #   configMapKeyRef:
          #     name: drupal-cm
          #     key: ALLOW_EMPTY_PASSWORD
        - name: MARIADB_HOST
          valueFrom:
            configMapKeyRef:
              name: drupal-cm
              key: MARIADB_HOST
        - name: MARIADB_PORT_NUMBER
          valueFrom:
            configMapKeyRef:
              name: drupal-cm
              key: MARIADB_PORT_NUMBER
        - name: DRUPAL_DATABASE_NAME
          valueFrom:
            secretKeyRef: # from secret
              name: drupal-secret
              key: DRUPAL_DATABASE_NAME
        - name: DRUPAL_DATABASE_USER
          valueFrom:
            secretKeyRef: # from secret
              name: drupal-secret
              key: DRUPAL_DATABASE_USER
        - name: DRUPAL_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef: # from secret
              name: drupal-secret
              key: DRUPAL_DATABASE_PASSWORD
        - name: DRUPAL_PROFILE
          valueFrom:
            configMapKeyRef:
              name: drupal-cm
              key: DRUPAL_PROFILE
        - name: DRUPAL_USERNAME
          valueFrom:
            configMapKeyRef:
              name: drupal-cm
              key: DRUPAL_USERNAME
        - name: DRUPAL_PASSWORD
          valueFrom:
            secretKeyRef: # from secret
              name: drupal-secret
              key: DRUPAL_PASSWORD
        - name: DRUPAL_EMAIL
          valueFrom:
            configMapKeyRef:
              name: drupal-cm
              key: DRUPAL_EMAIL
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          httpGet:
            path: "/user/login"
            port: 80
            scheme: HTTP
          initialDelaySeconds: 120
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: "/user/login"
            port: 80
            scheme: HTTP
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 6
        resources: {} # empty by now
        volumeMounts:
          - mountPath: /bitnami/drupal
            name: drupal-data
            subPath: drupal
          - mountPath: /bitnami/apache
            name: drupal-data
            subPath: apache
      volumes:
        - name: drupal-data
          persistentVolumeClaim:
            claimName: drupal-pvc