############################ # ############################
## Bitnami K8S training
## session01/exercise02
#
## Author: Antonio Gamez-Diaz
## Contact: antoniogamez@us.es
#
# File: drupal configmap creation
# Purpose: creates key/value pairs to be used in drupal
############################ # ############################
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: drupal-cm
  namespace: s02-exercise-01
  labels:
    app: drupal
    tier: frontend
data:
  ALLOW_EMPTY_PASSWORD: "no"
  MARIADB_HOST: mariadb
  MARIADB_PORT_NUMBER: "3306"
  DRUPAL_PROFILE: standard
  DRUPAL_USERNAME: antonio
  DRUPAL_EMAIL: antonio@example.com