# ############################ # ############################
# ## Bitnami K8S training
# ## session01/exercise02
# #
# ## Author: Antonio Gamez-Diaz
# ## Contact: antoniogamez@us.es
# #
# # File: wordpress pv claim creation
# # Purpose: allocates some persistence
# ############################ # ############################
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  namespace: s02-exercise-02
  labels:
    app: wordpress
    tier: frontend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
