apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-backup
  namespace: exercise-03
  labels:
    app: wordpress-backup
    type: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
