############################ # ############################
## Bitnami K8S training
## session01/exercise03-p02
#
## Author: Antonio Gamez-Diaz
## Contact: antoniogamez@us.es
#
# File: wordpress service
# Purpose: exposes a "wordpress" NodePort service
############################ # ############################
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: wordpress
  namespace: s02-exercise-03-p02
  labels:
    app: wordpress
    tier: frontend
spec:
  selector:
    app: wordpress
    tier: frontend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
    nodePort: 32081
  - name: https
    protocol: TCP
    port: 443
    targetPort: https
    nodePort: 32444
  type: NodePort