apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mariadb-backup
  namespace: exercise-02
  labels:
    app: mariadb-backup
    tier: backend
    release: production
spec:
  schedule: "* */6 * * *" # every 6 hours
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: mariadb-backup
            tier: backend
            release: production
        spec:
          securityContext:
            runAsUser: 1001
            fsGroup: 1001
          containers:
          - name: mariadb
            image: bitnami/mariadb:10.1
            command:
            - "/bin/bash"
            - "-c"
            - |
              mysqldump -h$BACKUP_HOST -u$BACKUP_USER -p$BACKUP_PASSWORD $BACKUP_DATABASE > /bitnami/mariadb-backup/backup_$(date +%Y%m%d.%H:%M).sql;
              find /bitnami/mariadb-backup/ -type f -name '*.sql' -mtime +7 -exec rm {} \;
            volumeMounts:
            - mountPath: /bitnami/mariadb-backup
              name: mariadb-backup
            resources:
              requests:
                cpu: "25m"
                memory: "250Mi"
              limits:
                cpu: "50m"
                memory: "500Mi"
            env:
              - name: BACKUP_HOST
                valueFrom:
                  configMapKeyRef:
                    name: frontend-config
                    key: mariadb-host
              - name: BACKUP_DATABASE
                valueFrom:
                  secretKeyRef:
                    name: database-credentials
                    key: wp-dbname
              - name: BACKUP_USER
                valueFrom:
                  secretKeyRef:
                    name: database-credentials
                    key: wp-user
              - name: BACKUP_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: database-credentials
                    key: wp-password
          restartPolicy: Never
          volumes:
          - name: mariadb-backup
            persistentVolumeClaim:
              claimName: mariadb-backup
