apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-backup
  namespace: exercise-02
  labels:
    app: mariadb-backup
    type: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
