---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb
  namespace: exercise-01
  labels:
    app: mariadb
type: Opaque  
data:
  root_password: MTZjMTZ2Mw==
  password: SWV4aWExdVY=
  database: Yml0bmFtaV93b3JkcHJlc3M=
  user: Ym5fd29yZHByZXNz
