apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress-canary
  namespace: exercise-01
  labels:
    app: wordpress
    iscanary: "true"
spec:
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: bitnami/wordpress:4.9.8
        name: wordpress
        envFrom:
        - configMapRef:
            name: wordpress
        env:
        - name: WORDPRESS_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: wordpress
              key: database_name
        - name: WORDPRESS_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: wordpress
              key: database_user
        - name: WORDPRESS_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress
              key: database_password
        - name: WORDPRESS_EMAIL
          valueFrom:
            secretKeyRef:
              name: wordpress
              key: wordpress_email
        ports:
        - name: wordpress-http
          containerPort: 80
        - name: wordpress-https
          containerPort: 443
        readinessProbe:
          tcpSocket:
            port: wordpress-http
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: wordpress-http
          initialDelaySeconds: 15
          periodSeconds: 20
