apiVersion: "v1"
kind: "Service"
metadata:
  name: myblog-mariadb-master
  namespace: exercise-02
  labels:
    app: myblog
    tier: backend
    role: master
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: myblog
    tier: backend
    role: master
  type: ClusterIP
